tap "homebrew/cask-fonts"

brew "deno"
brew "git"
brew "jq"
brew "mas"
brew "nvm"
brew "starship"

cask_args appdir: "~/Applications"
cask "1password"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "google-chrome"
cask "microsoft-edge"
cask "visual-studio-code"

mas "Magnet", id: 441258766