
# tap repositories and their packages

tap homebrew/core
brew aom
brew asdf
brew autoconf
brew automake
brew bdw-gc
brew brotli
brew c-ares
brew ca-certificates
brew cairo
brew coreutils
brew dav1d
brew deno
brew dnsmasq
brew fontconfig
brew freetype
brew gdbm
brew gettext
brew giflib
brew glib
brew gmp
brew highway
brew imath
brew jpeg-turbo
brew jpeg-xl
brew libpng
brew libpthread-stubs
brew libtiff
brew libtool
brew libvmaf
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew lzo
brew m4
brew mas
brew mpdecimal
brew openexr
brew openssl@1.1
brew pcre2
brew pixman
brew pkg-config
brew python@3.10
brew readline
brew sqlite
brew starship
brew unixodbc
brew webp
brew xorgproto
brew xz

tap homebrew/bundle

tap homebrew/cask-fonts
cask font-fira-code

tap homebrew/services

tap homebrew/cask
cask 1password
cask docker
cask firefox
cask google-chrome
cask google-cloud-sdk
cask notion
cask visual-studio-code

tap koenbollen/public

tap rcmdnk/file
brew brew-file

tap stripe/stripe-cli

tap superfly/tap

# App Store applications
appstore 408981434   iMovie     (10.3.5)
appstore 409183694   Keynote    (12.2)
appstore 405399194   Kindle     (1.39.0)
appstore 441258766   Magnet     (2.10.0)
appstore 409203825   Numbers    (12.2)
appstore 409201541   Pages      (12.2)
appstore 1451685025  WireGuard  (1.0.15)
appstore 497799835   Xcode      (14.1)
