
# tap repositories and their packages

tap homebrew/core
brew aom
brew bdw-gc
brew c-ares
brew cairo
brew dav1d
brew deno
brew dockutil
brew ffmpeg
brew flac
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew gdbm
brew gettext
brew giflib
brew git
brew glib
brew gmp
brew gnutls
brew gobject-introspection
brew graphite2
brew guile
brew harfbuzz
brew icu4c
brew jemalloc
brew jpeg
brew jq
brew lame
brew leptonica
brew libass
brew libassuan
brew libbluray
brew libev
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libidn2
brew libksba
brew libogg
brew libpng
brew libpthread-stubs
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libvidstab
brew libvorbis
brew libvpx
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew little-cms2
brew lzo
brew m4
brew mas
brew mpdecimal
brew nettle
brew nghttp2
brew npth
brew nvm
brew oniguruma
brew opencore-amr
brew openjdk
brew openjpeg
brew openssl@1.1
brew opus
brew p11-kit
brew pcre
brew pcre2
brew pinentry
brew pixman
brew pkg-config
brew python@3.9
brew rav1e
brew readline
brew rubberband
brew sdl2
brew snappy
brew speex
brew sqlite
brew srt
brew starship
brew tesseract
brew theora
brew unbound
brew webp
brew wget
brew x264
brew x265
brew xorgproto
brew xvid
brew xz
brew youtube-dl
brew zeromq
brew zimg

tap homebrew/bundle

tap homebrew/cask-fonts
cask font-fira-code

tap homebrew/cask
cask 1password
cask altair-graphql-client
cask docker
cask firefox
cask google-chrome
cask google-cloud-sdk
cask microsoft-auto-update
cask microsoft-edge
cask notion
cask visual-studio-code

tap rcmdnk/file
brew brew-file

tap stripe/stripe-cli
brew stripe

# App Store applications
appstore 682658836   GarageBand  (10.4.3)
appstore 408981434   iMovie      (10.2.5)
appstore 409183694   Keynote     (11.1)
appstore 441258766   Magnet      (2.6.0)
appstore 409203825   Numbers     (11.1)
appstore 409201541   Pages       (11.1)
appstore 497799835   Xcode       (12.5.1)
